Repository AY1920S1-CS2103-T11-1/main, pull requests merged in 2019-11, with the labels that each got.

#273 Completed Personal Portfolio Page
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Ahmed.adoc
  docs/team/atharvjoshi.adoc
  docs/team/hellopanda128.adoc
  docs/team/madanalogy.adoc
  docs/team/tirameshu.adoc
  docs/team/yoshi275.adoc
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/logic/parser/RegisterCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/IncidentManagerParserTest.java
  src/test/java/seedu/address/logic/parser/RegisterCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#275 Added Tests for List Persons
  docs/DeveloperGuide.adoc
  src/test/java/seedu/address/logic/commands/ListPersonsCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#277 Updated Name in AboutUs
  docs/AboutUs.adoc
Labels: type.Task

#278 Change access level for edit-i and delete-v commands
  docs/UserGuide.adoc
  docs/images/deleteVehicleNonAdmin.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteVehicleCommand.java
  src/main/java/seedu/address/logic/commands/EditIncidentCommand.java
  src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteVehicleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditIncidentCommandParser.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/EditIncidentCommandTest.java
  src/test/java/seedu/address/testutil/IncidentBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntities.java
Labels: type.Enhancement

#279 Set list-i parameter checking
  build.gradle
  docs/images/Untitled.png
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
  src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/parser/FindIncidentsCommandParserTest.java
Labels: priority.Medium, type.Bug, type.Task

#284 find-i allows multi word keywords
  docs/images/Untitled.png
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
  src/main/java/seedu/address/model/incident/DescriptionKeywordsPredicate.java
  src/main/java/seedu/address/model/incident/IdKeywordsPredicate.java
  src/main/java/seedu/address/model/incident/NameKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/FindIncidentsCommandParserTest.java
Labels: priority.High, type.Task

#289 Modify GUI with minor changes
  src/main/java/seedu/address/model/vehicle/Vehicle.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Task

#290 Update UG documentation on find-i
  docs/UserGuide.adoc
  docs/images/findIncidentsCommandWithDescriptionParameter.png
  docs/images/findIncidentsCommandWithDescriptionParameterFailed.png
  docs/images/findIncidentsCommandWithIdParameterFailed.png
  docs/images/findIncidentsCommandWithOperatorParameterFailed.png
  docs/images/findIncidentsCommandWithOperatorsParameter.png
  docs/images/findIncidentsCommandWithSelfParameter.png
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
Labels: priority.High, type.Task

#294 Typos & Tests
  docs/UserGuide.adoc
  docs/team/madanalogy.adoc
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement

#297 removed PPP edits made for printing
  docs/UserGuide.adoc
  docs/team/madanalogy.adoc
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Username.java
Labels: type.Task

#298 Add captions to list, find incidents in UG
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#301 Fix formatting of UG for list-i and find-i
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#307 Clear vehicle test case temporarily
  src/test/java/seedu/address/logic/commands/VehicleAssignmentCommandTest.java
Labels: priority.High, type.Bug

#306 Draft Yoshi275 ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ListIncidentsSequenceDiagram.puml
  docs/images/ListIncidentsSequenceDiagram.png
  docs/team/yoshi275.adoc
Labels: priority.High, type.Task

#311 added admin account if storage error
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/person/Username.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement

#315 added more sample accounts
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/madanalogy.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#316 updated image widths
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task

#321 Resolved Duplicate Username
  gradle/wrapper/gradle-wrapper 2.jar
  gradle/wrapper/gradle-wrapper 2.properties
  src/test/java/seedu/address/model/incident/IncidentDateTimeTest.java
Labels: type.Bug

#325 Updated Command Summary
  docs/UserGuide.adoc
  src/test/java/seedu/address/model/SessionTest.java
Labels: type.Bug

#332 Adding vehicle model tests
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/vehicle/AvailableInDistrictPredicate.java
  src/main/java/seedu/address/model/vehicle/District.java
  src/main/java/seedu/address/model/vehicle/UniqueVehicleList.java
  src/main/java/seedu/address/model/vehicle/Vehicle.java
  src/main/java/seedu/address/model/vehicle/VehicleType.java
  src/test/java/seedu/address/model/vehicle/AvailabilityTest.java
  src/test/java/seedu/address/model/vehicle/AvailableInDistrictPredicateTest.java
  src/test/java/seedu/address/model/vehicle/DistrictKeywordsPredicateTest.java
  src/test/java/seedu/address/model/vehicle/DistrictTest.java
  src/test/java/seedu/address/model/vehicle/UniqueVehicleListTest.java
  src/test/java/seedu/address/model/vehicle/VNumKeywordsPredicateTest.java
  src/test/java/seedu/address/model/vehicle/VTypeKeywordsPredicateTest.java
  src/test/java/seedu/address/model/vehicle/VehicleNumberTest.java
  src/test/java/seedu/address/model/vehicle/VehicleTest.java
  src/test/java/seedu/address/model/vehicle/VehicleTypeTest.java
  src/test/java/seedu/address/testutil/TypicalVehicles.java
Labels: priority.High, type.Task

#334 Adding manual testing
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/NewCommand.java
  src/main/java/seedu/address/logic/parser/NewCommandParser.java
Labels: priority.High, type.Task

#335 Change Incident creation default Description and CallerNumber fills
  src/main/java/seedu/address/model/incident/Incident.java
Labels: priority.High, type.Enhancement

#337 Establish assertions in predicate search
  src/main/java/seedu/address/model/incident/DescriptionKeywordsPredicate.java
  src/main/java/seedu/address/model/incident/IdKeywordsPredicate.java
  src/main/java/seedu/address/model/incident/NameKeywordsPredicate.java
Labels: priority.High, type.Task

#338 Fixed Person Model Diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug

#339 Fix Punctuation on find-i
  src/main/java/seedu/address/commons/util/StringUtil.java
Labels: priority.Medium, type.Bug

#341 minor edits for dg and ug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.Task

#343 Change GUI for Last Modified User Display
  src/main/java/seedu/address/ui/IncidentCard.java
Labels: priority.Low, type.Task

#350 Fix empty input for find-i
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
  src/main/java/seedu/address/model/incident/Description.java
  src/main/java/seedu/address/model/incident/DescriptionKeywordsPredicate.java
  src/main/java/seedu/address/model/incident/IncidentId.java
Labels: priority.High, type.Bug

#354 removed links that don't work and added mine
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Bug

#356 Update Yoshi275 PPP and UG
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yoshi275.adoc
Labels: priority.High, type.Task

#360 Add List Command test cases
  src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
  src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIncidents.java
Labels: priority.High, type.Task

#362 Update Developer Guide
  build.gradle
  docs/DeveloperGuide.adoc
  docs/team/madanalogy.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Username.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: type.Task

#364 Add Find Command testing
  src/test/java/seedu/address/logic/commands/FindIncidentsCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIncidents.java
Labels: priority.High, type.Task
