Repository AY1920S1-CS2103-T11-1/main, pull requests merged in 2019-10, with the labels that each got.

#16 Add UI mockup of IMS + Filling & Submitting features in UG
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: priority.High, type.Task

#9 About-Us + Update-DG + Update-UG
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Yoshi275.png
  docs/images/atharvjoshi.png
  docs/images/damithc.jpg
  docs/images/hellopanda128.png
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  docs/images/madanalogy.png
  docs/images/tirameshu.png
  docs/images/yijinl.jpg
  docs/images/yl_coder.jpg
  docs/team/Ahmed.adoc
  docs/team/Atharv.adoc
  docs/team/Cheryl.adoc
  docs/team/Mandy.adoc
  docs/team/MeiAn.adoc
  gradle/wrapper/gradle-wrapper.properties
Labels: priority.High, type.Task

#18 Update README.adoc to add Netlify status badge
  README.adoc
Labels: priority.Low, type.Enhancement

#19 Update Contact Us, Navbar Github Link
  docs/ContactUs.adoc
  docs/Documentation.adoc
Labels: priority.High, type.Task

#21 Updating UG
  README.adoc
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#20 Restructure README
  README.adoc
Labels: priority.High, type.Task

#28 Version 1.1
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#34 Model vehicle gui
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/vehicle/Availability.java
  src/main/java/seedu/address/model/vehicle/District.java
  src/main/java/seedu/address/model/vehicle/UniqueVehicleList.java
  src/main/java/seedu/address/model/vehicle/Vehicle.java
  src/main/java/seedu/address/storage/JsonAdaptedVehicle.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VehicleCard.java
  src/main/java/seedu/address/ui/VehicleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VehicleListCard.fxml
  src/main/resources/view/VehicleListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateEntityAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidEntityAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalEntitiesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.High, type.Task

#38 Update About Us
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/yoshi275.png
Labels: type.Task

#50 Add Incident model
  src/main/java/seedu/address/model/incident/Description.java
  src/main/java/seedu/address/model/incident/Incident.java
  src/main/java/seedu/address/model/incident/IncidentId.java
Labels: priority.High, type.Task

#56 Added Username & Password to Tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium, severity.Low, type.Task

#58 Basic Login Implementation
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/model/person/LoginCredentialsPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Enhancement

#64 Added Support for Dashes & Dots to Tags
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: severity.Low, type.Task

#66 Added Session Functionality
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlySession.java
  src/main/java/seedu/address/model/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#67 Implemented Login GUI Effect
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/IncidentListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/VehicleListPanel.fxml
Labels: priority.High, severity.Low, type.Enhancement

#69 Fixed Empty Display when Invalid Login
  src/main/java/seedu/address/logic/commands/LoginCommand.java
Labels: severity.Medium, type.Bug

#71 Added Session Details to Status Bar
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlySession.java
  src/main/java/seedu/address/model/Session.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement

#72 Added Coveralls & Codacy Badges
  README.adoc
Labels: type.Task

#86 implement edit feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/incident/CallerNumber.java
  src/main/java/seedu/address/model/incident/Description.java
  src/main/java/seedu/address/model/incident/Incident.java
  src/main/java/seedu/address/model/incident/IncidentDateTime.java
  src/main/java/seedu/address/model/incident/IncidentId.java
  src/main/java/seedu/address/storage/JsonAdaptedIncident.java
  src/main/java/seedu/address/ui/IncidentCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditIncidentBuilder.java
  src/test/java/seedu/address/testutil/IncidentBuilder.java
  src/test/java/seedu/address/testutil/IncidentUtil.java
Labels: priority.High, type.Task

#92 Implemented Update Command
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdatePersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/UpdatePersonDescriptorBuilder.java
Labels: priority.Medium, type.Enhancement

#93 Added Logout and Swap Commands
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SwapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#95 Fixed empty list login bug and session APIs
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Low, type.Task

#98 Update build.gradle
  build.gradle
Labels: type.Task

#88 NewCommand, SearchVehicleCommand
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/NewCommand.java
  src/main/java/seedu/address/logic/commands/SearchVehicleCommand.java
  src/main/java/seedu/address/logic/commands/SubmitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NewCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/incident/Incident.java
Labels: priority.High

#100 Add incident search operator flag
  src/main/java/seedu/address/logic/commands/SearchIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SearchIncidentsCommandParser.java
  src/main/java/seedu/address/model/incident/NameKeywordsPredicate.java
Labels: priority.Medium, type.Enhancement

#102 Update search variable names
  src/main/java/seedu/address/logic/commands/SearchIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SearchIncidentsCommandParser.java
  src/test/java/seedu/address/logic/parser/SearchIncidentsCommandParserTest.java
Labels: priority.Low, type.Task

#104 Update developer guide headers
  docs/DeveloperGuide.adoc
Labels: priority.Medium, type.Task

#106 Fixed JsonSerializableTest for Typical Entities
  src/main/java/seedu/address/model/incident/Incident.java
  src/main/java/seedu/address/model/incident/IncidentId.java
  src/test/data/JsonSerializableAddressBookTest/typicalEntitiesAddressBook.json
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalEntities.java
Labels: severity.Medium, type.Bug

#118 Completed Access Control Documentation
  .gitignore
  docs/DeveloperGuide.adoc
  docs/diagrams/AccessActivityDiagram.puml
  docs/diagrams/AccessSequenceDiagram.puml
  docs/images/AccessActivityDiagram.png
  docs/images/AccessSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Session.java
Labels: type.Bug, type.Task

#122 Update Developer Guide
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: type.Enhancement, type.Task

#123 Minor Aesthetic Updates to DG
  docs/DeveloperGuide.adoc
Labels: type.Task

#125 Add SearchIncidents and ListIncidents Implementation to Developer's Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/ListIncidentsSequenceDiagram.puml
  docs/diagrams/SearchIncidentsSequenceDiagram.puml
  docs/images/ListIncidentsSequenceDiagram.png
  docs/images/SearchIncidentsSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
Labels: priority.High, type.Task

#128 Remove Unused Implementation Explanations from DG
  docs/DeveloperGuide.adoc
Labels: priority.Low, type.Task

#139 Fix vehicles listing command
  src/main/java/seedu/address/logic/commands/ListVehiclesCommand.java
  src/main/java/seedu/address/model/Model.java
Labels: priority.High, type.Bug

#156 Implemented Access Control
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonsCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonsCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SwapCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/ListPersonsCommandParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/Session.java
  src/main/java/seedu/address/model/person/LoginCredentialsPredicate.java
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Username.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntities.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#157 Updated User Guide and Other Improvements
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlySession.java
  src/main/java/seedu/address/model/Session.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/parser/IncidentManagerParserTest.java
Labels: type.Enhancement, type.Task

#170 Update Developer Guide with FillCommand, SubmitCommand, Incident Model Implementation and Diagrams
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/FillCommandNoParamsSequenceDiagram.puml
  docs/diagrams/FillCommandWithParamsSequenceDiagram.puml
  docs/diagrams/IncidentClassDiagram.puml
  docs/diagrams/IncidentReportingActivityDiagram.puml
  docs/images/FillCommandNoParamsSequenceDiagram.png
  docs/images/FillCommandWithParamsSequenceDiagram.png
  docs/images/IncidentClassDiagram.png
  docs/images/IncidentReportingActivityDiagram.png
  docs/images/fillCommandSequenceDiagramNoParams.png
  docs/images/fillCommandSequenceDiagramWithoutParams.png
Labels: priority.High, type.Task

#185 Fix broken incidents ID search
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
Labels: priority.High, type.Task

#189 Fix search return message for either one or zero returned incidents, persons and vehicles
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonsCommand.java
  src/main/java/seedu/address/logic/commands/FindVehiclesCommand.java
  src/test/java/seedu/address/logic/commands/FindPersonsCommandTest.java
  src/test/java/seedu/address/logic/commands/FindVehiclesCommandTest.java
Labels: priority.Low, type.Task

#192 Abstract messages from ListIncidentsCommand to Message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListIncidentsCommand.java
  src/test/java/seedu/address/logic/commands/ListIncidentsCommandTest.java
Labels: priority.Medium, type.Task

#173 Update User Guide with ListIncidentsCommand and FindIncidentsCommand
  docs/UserGuide.adoc
  docs/images/findIncidentsCommandWithDescriptionParameter.png
  docs/images/findIncidentsCommandWithDescriptionParameterFailed.png
  docs/images/findIncidentsCommandWithIdParameter.png
  docs/images/findIncidentsCommandWithIdParameterFailed.png
  docs/images/findIncidentsCommandWithOperatorParameter.png
  docs/images/findIncidentsCommandWithOperatorParameterFailed.png
  docs/images/listIncidentsCommand.png
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
Labels: priority.High, type.Task

#194 Add add-v command for adding vehicles
  src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
  src/main/java/seedu/address/logic/commands/EditIncidentCommand.java
  src/main/java/seedu/address/logic/parser/AddVehicleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/incident/Incident.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/IncidentBuilder.java
Labels: priority.High, type.Task

#195 Add DeleteVehicleCommand
  src/main/java/seedu/address/logic/commands/DeleteVehicleCommand.java
  src/main/java/seedu/address/logic/parser/DeleteVehicleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditVehicleCommandParser.java
  src/main/java/seedu/address/logic/parser/IncidentManagerParser.java
  src/main/java/seedu/address/model/IncidentManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#199 Updated Ui Image
  README.adoc
  docs/AboutUs.adoc
  docs/images/Ui.png
Labels: type.Task

#200 Update user guide
  docs/UserGuide.adoc
  docs/images/addVehicle1.png
  docs/images/addVehicle2.png
  docs/images/deleteVehicle1.png
  docs/images/deleteVehicle2.png
  docs/images/editDuplicateVeh1.png
  docs/images/editDuplicateVeh2.png
  docs/images/editIncident1.png
  docs/images/editIncident2.png
  docs/images/editVehicle1.png
  docs/images/editVehicle2.png
Labels: type.Task

#204 Add self-search for find-incidents
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
Labels: priority.Medium, type.Enhancement

#208 Add multi-parameter search for find-i
  src/main/java/seedu/address/logic/commands/FindIncidentsCommand.java
  src/main/java/seedu/address/logic/parser/FindIncidentsCommandParser.java
  src/test/java/seedu/address/logic/parser/FindIncidentsCommandParserTest.java
Labels: priority.High, type.Enhancement

#210 Minor Edits
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SessionClassDiagram.puml
  docs/images/SessionClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonsCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonsCommand.java
  src/main/java/seedu/address/logic/parser/ListPersonsCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task

#215 Updated UI Screenshot
  build.gradle
  docs/images/Ui.png
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Session.java
  src/main/java/seedu/address/model/person/Password.java
  src/main/java/seedu/address/model/person/Username.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/LoginCredentialsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PasswordTest.java
  src/test/java/seedu/address/model/person/UsernameTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
Labels: type.Task
